City: Chicago
Country: United States
Description: ITB site for Tier 3 and small sites prototyping and testing at the University
  of Chicago.
ID: 10134
Latitude: 41.790593
Longitude: -87.600936
State: IL
Zipcode: '60637'
