Department: Plant Biology
Description: Phenotyping leaf epidermis by optical tomography and computer vision
  to evaluate stomatal patterning across natural diversity and transgenic lines of
  Sorghum and Setaria
FieldOfScience: Plant Biology
ID: '430'
Name: WEST
Organization: University of Illinois Urbana-Champaign
PIName: Dr. Andrew Leakey
Sponsor:
  CampusGrid:
    Name: OSG Connect
