Department: Plant Biology
Description: Phenotyping leaf epidermis by optical tomography and computer vision
  to evaluate stomatal patterning across natural diversity and transgenic lines of
  Sorghum and Setaria
FieldOfScience: Biological sciences
ID: '430'
Organization: University of Illinois Urbana-Champaign
PIName: Dr. Andrew Leakey
Sponsor:
  CampusGrid:
    Name: OSG Connect
