AddressLine1: "R. Dr. Bento Teobaldo Ferraz 271 - Bl. II - Barra Funda - Sao Paulo"
City: Sao Paulo
Country: Brazil
ID: 10017
Latitude: -23.52433
LongName: SAO PAULO RESEARCH AND ANALYSIS CENTER
Longitude: -46.665469
State: Sao Paulo
Zipcode: 01140-070
