LongName: Lehigh University Hawk Cluster
Description: NSF Award ID 2019035 Computing Cluster
ID: 10298
AddressLine1: 8B E. Packer Ave
AddressLine2: Room 172
City: Bethlehem
Country: USA
State: Pennsylvania
Zipcode: "18015"
Latitude: 40.609049
Longitude: -75.378569
