AddressLine1: 155 South 1452 East Room 405
City: Salt Lake City
Country: United States
Description: University of Utah's central Research Computing facility located in Salt
  Lake City, with multiple services including Virtual environments, HIPAA protected
  environments for Research, and classic X86 based HPC clusters - mainly with Infiniband
  interconnects.
ID: 10268
Latitude: 40.7608
LongName: Center for Research and High Performance Computing Notchpeak cluster
Longitude: -111.891
State: UT
Zipcode: '84112'
