City: Urbana
Country: United States
Description: University of Illinois at Urbana-Champaign's Campus Cluster for MWT2
ID: 10311
LongName: University of Illinois at Urbana-Champaign Campus Cluster
Latitude: 40.109647
Longitude: -88.3
State: IL
Zipcode: '61801'
