# LongName is the expanded name of the site
LongName: University of Tennessee Chatanooga
# Description is a brief description of your site
Description: University of Tennessee Chatanooga Epyc Cluster

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10296

# AddressLine1 is the street address of the site
AddressLine1: 735 Vine St
### AddressLine2 (optional) is the second line of the street address
AddressLine2: University of Tennessee Chatanooga
# City is the city the site is located in
City: Chatanooga

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
State: TN
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "37403"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 35.046483
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -85.295502
