AddressLine1: 4545 15th Ave NE
City: Seattle
Country: United States
ID: 10193
Latitude: 47.655316
LongName: University of Washington Information Technology
Longitude: -122.303546
State: WA
Zipcode: '98105'
