LongName: Scotgrid Edinburgh Compute and Data Facility
Description: Scotgrid facility at the University of Edinburgh
ID: 10317
AddressLine1: Old College, South Bridge
City: Edinburgh
Country: United Kingdom
Zipcode: 'EH8 9YL'

Latitude: 55.9445
Longitude: -3.1892
