AddressLine1: 191 W Woodruff Ave
City: Columbus
Country: United States
Description: CMS Tier3 at The Ohio State University
ID: 10100
Latitude: 40.003407
Longitude: -83.014476
State: OH
Zipcode: '43210'
