#!/bin/env python

import sys
import hashlib

if len(sys.argv) < 2:
    sys.exit("usage: %s <EMAIL> [<EMAIL 2>..<EMAIL N>]" % sys.argv[0])

for string in sys.argv[1:]:
    print hashlib.sha1(string).hexdigest()
