#!/bin/bash

if [[ $# -lt 1 || $1 = -h || $1 = --help ]]; then
    echo "Usage: ${0##*/} <output file> [<mysql options>]"
    exit 2
fi

outfile=$1
shift
mysql --batch "$@" > "$outfile" <<__EOF__
USE oim;
SELECT
    site.id AS ID,
    site.name AS Name,
    site.long_name AS LongName,
    site.description AS Description,
    site.address_line_1 AS AddressLine1,
    site.address_line_2 AS AddressLine2,
    site.state AS State,
    site.zipcode AS Zipcode,
    site.country AS Country,
    site.longitude AS Longitude,
    site.latitude AS Latitude
    FROM oim.site
;
__EOF__
sed -i -e "s/\r//g" "$outfile"
