# LongName is the expanded name of the site
LongName: University of Colorado Denver
# Description is a brief description of your site
Description: University of Colorado Denver

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10338

# AddressLine1 is the street address of the site
AddressLine1: 1201 Larimer Street
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Denver

# Country is the country the site is located in
Country: United States
### State (optional) is the state or province the site is located in
# State: Wisconsin
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: 80204

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 39.7466611
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -105.0023241
