AddressLine2: 107 N MONROE STREET
City: Stillwater
Country: United States
Description: Hosted BOSCO CE for the OSU Cowboy cluster
ID: 10223
Latitude: 36.1230911
Longitude: -97.0723655
State: OK
Zipcode: '74078'
