AddressLine1: 414 E Clark St
City: Vermillion
Country: United States
Description: Hosted CE for Legacy cluster at University of South Dakota
ID: 10230
Latitude: 42.788065
Longitude: -96.924136
State: SD
Zipcode: '57069'
