AddressLine1: Central Park West at 79th St.
City: New York
Country: USA
Description: The American Museum of Natural History is one of the world's preeminent scientific and cultural institutions.
ID: 10244
Latitude: 40.7128
LongName: American Museum of Natural History
Longitude: -74.0060
State: NY
Zipcode: 10024-5192
