ID: 10350
LongName: Internet2 Amsterdam
Description: Backbone location of Internet2 at the Amsterdam Point of Presence
Latitude: 52.3824
Longitude: 4.8995
City: Amsterdam
State: North Holland
Country: Netherlands