AddressLine1: 222 W. Washington Ave
AddressLine2: Suite 500
City: Madison
Country: United States
Description: The Wisconsin IceCube Particle Astrophysics Center houses multiple Particle
  Astrophysics projects with the IceCube Neutrino Observatory being the largest.
ID: 10188
Latitude: 43.070725
LongName: Wisconsin IceCube Particle Astrophysics Center
Longitude: -89.388464
State: WI
Zipcode: '53703'
