# LongName is the expanded name of the site
LongName: Chameleon Cloud at the University of Chicago
# Description is a brief description of your site
Description: Theory and Computing Sciences Building at Argonne National Laboratory

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10294

# AddressLine1 is the street address of the site
AddressLine1: 9700 S. Cass Ave
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Lemont

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
State: Illinois
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "60439"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 41.71833
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -87.98237
