LongName: University of Wyoming
AddressLine1: 1000 E University Ave
Country: United States
Description: University of Wyoming Advanced Research Computing Center
Latitude: 41.314986
Longitude: -105.564322
City: Laramie
State: Wyoming
Zipcode: '82071'
