LongName: The DV (central IT) group at Deutsches Elektronen-Synchrotron (DESY) Zeuthen campus
Description: The DV group at DESY-ZN
AddressLine1: Platanenallee 6
City: Zeuthen
Country: Germany
Zipcode: D-15738
Latitude: 52.345173
Longitude: 13.633461
