City: College Station
Country: United States
ID: 10117
Latitude: 30.619803
LongName: TAMU Academy for Advanced Telecommunications and Learning Technologies
Longitude: -96.342672
State: Texas
Zipcode: 77843-3139
