AddressLine1: Orchard Rd.
City: Hampton
Country: United States
Description: The Atlas Tier3 Cloud in Particle Physics Computing Facility at Hampton
  University.
ID: 10145
Latitude: 37.019576
LongName: Hampton ATLAS Tier3
Longitude: -76.336344
State: VA
Zipcode: '23668'
