AddressLine1: 600 W. College Avenue
City: Tallahassee
Country: United States
Description: Hosted CE for GlueX and OSG support
ID: 10232
Latitude: 30.441822
Longitude: -84.2985
State: FL
Zipcode: '32306'
