LongName: PATh Resources at FIU
Description: Resources owned by the PATh project located at Florida International University

ID: 10318

AddressLine1: 11200 SW 8th St
#AddressLine2: PC417
City: Miami
Country: United States
State: Florida
Zipcode: '33174'

Latitude: 25.758
Longitude: -80.376
