AddressLine1: Physics Building, room D-132
AddressLine2: Stony Brook University
City: Stony Brook
Country: United States
Description: Stony Brook Atlas Tier3 Cluster
ID: 10124
Latitude: 40.916269
Longitude: -73.126116
State: New York
Zipcode: 11794-3800
