AddressLine1: 1320 E 10th Street
City: Bloomington
Country: United States
Description: Information and Library Sciences
ID: 10177
Latitude: 39.17099515330087
LongName: Information and Library Sciences
Longitude: -86.51753783226013
State: IN
Zipcode: '47405'
