LongName: University of Connecticut Xanadu HPC Resource
Description: Xanadu HPC Resource
ID: 10297
AddressLine1: Engineering and Sciences Building (ESB)
City: Storrs
Country: United States
State: Connecticut
Zipcode: "06269-3138"
Latitude: 41.8084
Longitude: -72.2495
