AddressLine1: 727 E 3rd St
AddressLine2: Swain Hall West 117
City: Bloomington
Country: United States
Description: Indiana University Physics tier 3 cluster.
ID: 10129
Latitude: 39.16474
Longitude: -86.524579
State: Indiana
Zipcode: 47405-7105
