LongName: PATh Resources at UW-Madison
AddressLine1: 1210 W. Dayton St
City: Madison
Country: United States
Description: >-
  Resourcesd owned by the PATh project located at the University of
  Wisconsin-Madison
ID: 10337
Latitude: 43.071568
Longitude: -89.406931
State: Wisconsin
Zipcode: 53706-1685
