AddressLine1: Department of Physics
AddressLine2: Bellarmine University
City: Louisville
Country: United States
Description: Bellarmine University ATLAS Tier3 Site
ID: 10119
Latitude: 38.219681
LongName: Bellarmine University
Longitude: -85.703713
State: Kentucky
Zipcode: '40205'
