AddressLine1: 1 Cyclotron Road Mail stop 50A-311
City: Berkeley
Country: United States
Description: 'perfSONAR testbed instance at LBL.  NOTE: Not on LHCONE'
ID: 10202
Latitude: 37.401394
LongName: LBL ESnet
Longitude: -116.867846
State: CA
Zipcode: '94720'
