ID: 10362
LongName: SingAREN data center
Description: Backbone location of SingAREN
Latitude: 1.2961438422403178
Longitude: 103.79088279998233
City: Singapore
State: Singapore
Country: Republic of Singapore
