LongName: University-of-Manitoba-Grex
Description: Grex HPC system located at University of Manitoba High Performance Computer Centre (HPCC)
AddressLine1: 188 Dysart rd 
City: Winnipeg
Country: Canada
State: MB
Zipcode: "R3T 2N2"
Latitude: 49.810788548024476 
Longitude: -97.13350278225465
