LongName: Karlsruhe Institute of Technology (KIT) Scientific Computing Center (SCC)
Description: The SCC at KIT
AddressLine1: Hermann-von-Helmholtz-Platz 1
City: Eggenstein-Leopoldshafen
Country: Germany
Zipcode: 76344
Latitude: 49.096
Longitude: 8.432
