AddressLine1: Rua do Matao, Travessa R 187
AddressLine2: Cidade Universitaria
City: Sao Paulo
Country: Brazil
Description: SAMPA site is T2 of WLHC
ID: 10200
Latitude: -23.559086
LongName: "GRupo de \xCDons PEsados Relativ\xEDsticos - GRIPER"
Longitude: -46.735994
State: SP
Zipcode: 05508-900
