AddressLine1: Tate Lab of Physics
AddressLine2: 116 Church Street Se
City: Minneapolis
Country: United States
ID: 10113
Latitude: 44.988841
LongName: University of Minnesota School of Physics and Astronomy
Longitude: -93.264999
State: Minnesota
Zipcode: '55455'
