AddressLine1: Kennesaw State University, Department of Biology and Physics
AddressLine2: 1000 Chastain Road
City: Kennesaw
Country: United States
Description: Kennesaw State University is a member of the Belle and Belle II collaborations
ID: 10182
Latitude: 34.0226996
Longitude: -84.581597
State: Georgia
Zipcode: 30144-5591
