LongName: PATh Resources at Syracuse
Description: >-
  Resources owned by the PATh project located at Syracuse University.

ID: 10346

AddressLine1: 900 South Crouse Ave
City: Syracuse
Country: United States
State: New Yorkk
Zipcode: '13244'

Latitude: 43.0391534
Longitude: -76.1373045
