AddressLine1: 1111 South University Parks Drive
City: Waco
Country: United States
Description: Baylor University OSG Site
ID: 10226
Latitude: 31.5498
LongName: Baylor University
Longitude: -97.1143
State: TX
Zipcode: '76706'
