LongName: PATh Resources at UNL
Description: >-
  Resources owned by the PATh project located at the University of
  Nebraska-Lincoln

ID: 10335

AddressLine1: 118 Schorr Center
City: Lincoln
Country: United States
State: Nebraska
Zipcode: '68588'

Latitude: 40.819818
Longitude: -96.705651
