# LongName is the expanded name of the site
LongName: University of XYZ Cluster
# Description is a brief description of your site
Description: Computer Science building of the University of XYZ

# ID is a unique ID acquired by running "bin/next_site_id" from the topology repo
ID: 10238

# AddressLine1 is the street address of the site
AddressLine1: 1234 Fifth St
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
# State: Wisconsin
### Zipcode (optional) is the zipcode/postal code of the site
# Zipcode: "01234"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 54.40
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -90.01

