AddressLine1: 360 Huntington Ave
City: Boston
Country: United States
Description: Northeastern University CMS Tier 3
ID: 10191
Latitude: 42.33787
LongName: Northeastern University CMS Tier 3
Longitude: -71.08919
State: MA
Zipcode: '02115'
