AddressLine1: Redwood Building
AddressLine2: King Edward VII Avenue
City: Cardiff
Country: UK
Description: LIGO Cardiff Computing Cluster
ID: 10254
Latitude: 51.4879593
LongName: Cardiff Computing Cluster
Longitude: -3.186923
Zipcode: CF10 3NB
