  
LongName: Southern Illinois University Edwardsville CC Cluster
Description: SIUE CC Cluster

ID: 10299

AddressLine1: SIUE State Route 157
City: Edwardsville

Country: United States
State: Illinois
Zipcode: "62026"


Latitude: 38.7931
Longitude: -89.9961
