AddressLine1: 94 Durham Center
AddressLine2: 613 Morrill Road
City: Ames
Country: United States
Description: Iowa State University HPC Group Cluster
ID: 
Latitude: 42.027
Longitude: -93.650
State: IA
Zipcode: '50011'
