GroupDescription: The University of Manitoba GREX cluster
GroupID: [TO_BE_ASSIGNED_BY_OSG]
Production: true
Resources:
  UniversityOfManitoba-GREX:
    Active: true
    ContactLists:
      Administrative Contact:
        Primary:
          ID: OSG1001305
          Name: Grigory Shamov
        Secondary:
          ID: OSG1001354
          Name: Kamrul Shaker
      Security Contact:
        Primary:
          Name: Grigory Shamov
          ID: OSG1001305
        Secondary:
          Name: Kamrul Shaker
          ID: OSG1001354
    Description: The CE serving UniversityOfManitoba-GREX cluster, providing compute resources for OSG users.
    FQDN: grex-osg-ce-01.hpc.umanitoba.ca
    ID: [TO_BE_ASSIGNED_BY_OSG]
    Services:
      CE:
        Description: Compute Element
        Details:
          hidden: false
          sam_uri: htcondor://grex-osg-ce-01.hpc.umanitoba.ca
