# LongName is the expanded name of the site
LongName: Lamar University
# Description is a brief description of your site
Description: Lamar University Cluster

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10295

# AddressLine1 is the street address of the site
AddressLine1: 907 Iowa Ave
### AddressLine2 (optional) is the second line of the street address
AddressLine2: Lamar University
# City is the city the site is located in
City: Beaumont

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
State: TX
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "77705"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 30.038388
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -94.074729
