City: Bloomington
Country: United States
Description: 'Grouping of OSG GOC Staff VMs running various ITB Services: CE, SE,
  GUMS, etc'
ID: 10170
Latitude: 39.174239
Longitude: -86.500726
Zipcode: '47408'
