LongName: IN2P3-CC
Description: IN2P3-CC
AddressLine1: 21 avenue Pierre de Coubertin.
City: Villeurbanne
Country: France
LongName: IN2P3-CC
Description: IN2P3 Tier 1
Latitude: 45.78
Longitude: 4.87
State: Rhone-Alpes
Zipcode: 69100