name: Check Project FOS Precision
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.9.15
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ./.github/scripts/check_project_fos_precision/requirements.txt
      - run: python ./.github/scripts/check_project_fos_precision/main.py
